name: kmp_xlog
targets:
  kmp_xlog:
    type: library.static
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - path: ../objcCommon/objc
    dependencies:
      - framework: ../objcCommon/frameworks/mars.xcframework
        link: true
    settings:
      LIBRARY_SEARCH_PATHS: "$(inherited)"
      OTHER_LDFLAGS: "$(inherited)"
      USER_HEADER_SEARCH_PATHS: "$(inherited)"
      CONFIGURATION_BUILD_DIR: "$(PROJECT_DIR)/build/"
      CLANG_WARN_DOCUMENTATION_COMMENTS: "NO"
      CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER: "NO"
      ENABLE_BITCODE: "NO"
      ONLY_ACTIVE_ARCH: "NO"
      VALID_ARCHS: "arm64 x86_64"
      SKIP_INSTALL: "YES"
